import type { Metadata } from 'next'
import './globals.scss'
import { ChakraProvider } from './ChakraProvider'

export const metadata: Metadata = {
  title: 'Interface test',
  description: 'Generated by create next app',
  viewport: {
    width: 'device-width',
    initialScale: 1,
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body>
        <ChakraProvider>{children}</ChakraProvider>
      </body>
    </html>
  );
}
